repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: destroyed-symlinks
      - id: trailing-whitespace  # Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-merge-conflict  # Check for files that contain merge conflict strings
#      - id: double-quote-string-fixer  # Replace double quoted strings with single quoted strings
      - id: end-of-file-fixer  # Make sure files end in a newline and only a newline
      #      - id: requirements-txt-fixer  # Sort entries in requirements.txt and remove incorrect entry for pkg-resources==0.0.0
      - id: fix-encoding-pragma  # Remove the coding pragma:
        args: [ "--remove" ]
      - id: mixed-line-ending  # Replace or check mixed line ending
        args: [ "--fix=lf" ]
      #      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-added-large-files
#      - id: detect-aws-credentials
#        args: [ "--allow-missing-credentials" ]
      - id: debug-statements
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-docstring-first
      - id: check-case-conflict
      - id: forbid-new-submodules
#      - id: name-tests-test
#        args:
#          - --pytest-test-first

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports

  - repo: https://gitee.com/ibopo/pre-commit-hooks
    rev: v2.3.0
    hooks:
#      - id: forbid-chinese
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]

  #  - repo: https://github.com/psf/black
  #    rev: 23.3.0
  #    hooks:
  #      - id: black
  #        language_version: python3.9
  #
  #  - repo: https://github.com/pycqa/isort
  #    rev: 5.12.0
  #    hooks:
  #      - id: isort
  #        name: isort (python)
  #
  #  - repo: https://github.com/Riverside-Healthcare/djLint
  #    rev: v1.25.0
  #    hooks:
  #      - id: djlint-django

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-export
        args: [
          "-f", "requirements.txt",
          "-o", "requirements.txt",
          "--without-hashes",
          "--without-urls"
        ]


  - repo: https://github.com/mattlqx/pre-commit-sign
    rev: v1.1.3
    hooks:
      - id: sign-commit

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0a5
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

#  - repo: local
#    hooks:
#      - id: secure
#        name: trivy fs scans
#        entry: trivy
#        language: fail
#        args: [ "fs", "--scanners", "vuln","." ]

#  - repo: https://github.com/charliermarsh/ruff-pre-commit
#    rev: 'v0.0.264'
#    hooks:
#      - id: ruff

#  - repo: git://github.com/matthorgan/pre-commit-conventional-commits
#    rev: master
#    hooks:
#      - id: conventional-commit-check
#        stages:
#          - commit-msg
exclude: |
  (?x)^(
    docs\/.*|
    assets\/.*|
    scripts\/.*|
    runtime\/.*|
    fixtures\/.*|
    credentials\/.*|
    admin_env_notice\/.*|
    admin_shortcuts\/.*|
    .envs\/.*|
    .*migrations\/.*|
    \.coveragerc|
    setup\.cfg|
    fabfile\.py|
    .*?proto.*|
    .*?\.html|
    .*?\.yaml|
    .*?\.yml|
    .*?\.css|
    .*?\.pem|
    .*?\.key|
    .*?\.md|
    .*?\.js
  )

#exclude: .*migrations\/.*
default_stages: [ commit ]
